---
- job:
    name: foo
    pre-run: playbooks/foo-pre.yaml

- job:
    name: bar
    run: playbooks/foo-pre.yaml
    required-projects:
      - name: org/project1
        override-checkout: master

- project:
    name: "foo"
    templates:
      - "template1"
    check:
      jobs:
        - foo
        - bar
    gate:
      jobs:
        - foo
        - bar
